#!/usr/bin/with-contenv bash
################################################################################
# This is property of eXtremeSHOK.com
# You are free to use, modify and distribute, however you may not remove this notice.
# Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################
#
# openlitespeed is unable to directly log to /dev/stdout , so we need to tail the log directly
#
# find a solution to tail as nobody
#exec s6-setuidgid nobody tail -F -n 0 /usr/local/lsws/logs/error.log /usr/local/lsws/logs/modsec.log
echo "Monitoring error.log" >> /usr/local/lsws/logs/error.log && echo "Monitoring modsec.log" >> /usr/local/lsws/logs/modsec.log && tail -F -n 1 /usr/local/lsws/logs/error.log /usr/local/lsws/logs/modsec.log
