#!/usr/bin/with-contenv sh

if [ -f /xshok-init.sh ] ; then
  while ! bash /xshok-init.sh ; do
    echo "Waiting for init to complete"
    sleep 5s
  done
fi

# s6-nice used to set the nice value of openlitespeed to -10, will warn if it cannot be set
#/bin/s6-nice -I -n -10 /usr/local/lsws/bin/openlitespeed -d

#/bin/s6-nice -I -n -10 /usr/local/lsws/bin/openlitespeed -d

exec /usr/local/lsws/bin/openlitespeed -d
#
# while true; do
#   if ! /usr/local/lsws/bin/lswsctrl status | grep -q "litespeed is running with PID" ; then
# 		break
# 	fi
# 	sleep 60
# done
