#!/usr/bin/with-contenv bash
################################################################################
# This is property of eXtremeSHOK.com
# You are free to use, modify and distribute, however you may not remove this notice.
# Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################

if [ -f /xshok-vhost-fix-permissions.sh ] ; then
  echo "Launching xshok-vhost-fix-permissions.sh"
  bash /xshok-vhost-fix-permissions.sh
  #run once every 7 days
  sleep 7d
fi
