#!/usr/bin/with-contenv bash
################################################################################
# This is property of eXtremeSHOK.com
# You are free to use, modify and distribute, however you may not remove this notice.
# Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################

# restart openlitespeed when changes to the vhost/domain.com/cert dirs are detected
# when a chnage is detected, it will restart litespeed after waiting for 300seconds
# requires python3-watchdog

if [ -f /xshok-fix-permissions.sh ] ; then

  sleep 7d
fi

WATCHMEDO_ENABLE

while ! /usr/local/lsws/bin/lswsctrl status | grep -q "litespeed is running with PID" ; do
	echo "Waiting for OpenLiteSpeed to start"
  sleep 30s
done

while true ; do
  #watchmedo shell-command --ignore-patterns="/var/www/vhosts/*/acme/*;/var/www/vhosts/*/dbinfo/*;/var/www/vhosts/*/html/*;/var/www/vhosts/*/logs/*;/var/www/vhosts/*/sql/*;/var/www/vhosts/*/logs/*;/var/www/vhosts/*/backup/*;" --patterns="/var/www/vhosts/*/certs/*.pem" --ignore-directories --recursive --wait --drop --timeout 30 /var/www/vhosts --command='echo "${watch_src_path} - ${watch_dest_path} - ${watch_event_type} - ${watch_object}"'
  watchmedo shell-command --ignore-patterns="/var/www/vhosts/local.domain/*;/var/www/vhosts/local/*;/var/www/vhosts/localhost/*;/var/www/vhosts/localdomain/*;/var/www/vhosts/sample/*;/var/www/vhosts/example/*;/var/www/vhosts/*/acme/*;/var/www/vhosts/*/dbinfo/*;/var/www/vhosts/*/html/*;/var/www/vhosts/*/logs/*;/var/www/vhosts/*/sql/*;/var/www/vhosts/*/logs/*;/var/www/vhosts/*/backup/*;" --patterns="/var/www/vhosts/*/certs/*.pem" --ignore-directories --recursive --wait --drop --timeout 300 /var/www/vhosts --command='echo "${watch_src_path} : ${watch_event_type}, sleeping for 300s" && sleep 300 && echo "restarting litespeed" && /usr/local/lsws/bin/lswsctrl restart'
  echo "watchmedo quit, sleeping for 60s and then reloading"
  sleep 60s
done
