#!/usr/bin/with-contenv bash
################################################################################
# This is property of eXtremeSHOK.com
# You are free to use, modify and distribute, however you may not remove this notice.
# Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################

if [ -f /xshok-fix-permissions.sh ] ; then
  echo "Launching fix-permissions"
  bash /xshok-fix-permissions.sh
fi
