#!/usr/bin/with-contenv bash
################################################################################
# This is property of eXtremeSHOK.com
# You are free to use, modify and distribute, however you may not remove this notice.
# Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################

if [ -f /xshok-init-pre.sh ] ; then
  echo "Launching init-pre"
  bash /xshok-init-pre.sh
fi

if [ -f /xshok-init.sh ] ; then
  echo "Launching init"
  bash /xshok-init.sh
fi

if [ -f /xshok-init-post.sh ] ; then
  while true ; do
    echo "Launching init-post"
    bash /xshok-init-post.sh
    sleep 5s
  done
fi
